### ISSUE TITLE
 Shipping Guide API 1.0 will finally be decomissoned on 01.07.2021 - will this extension work ?

### ISSUE THREAD

**Issue by GrzegorzDrozd** [markant-norge/magento2-bring#17]
Hi,

 Shipping Guide API 1.0 will finally be decomissoned on 01.07.2021. Will this extension work ?
![image](https://user-images.githubusercontent.com/1885137/121695641-872d5900-cacb-11eb-8b44-e7dd1ceecc91.png)

**Comment by gitforfareedi** [comment]
Yes we are already using 2.0 API.
