### ISSUE TITLE
Same pickup point for all customers

### ISSUE THREAD

**Issue by jBjerkli** [markant-norge/magento2-bring#19]
I am aware that this might be a misconfig, but in that case I am unable to figure out where it is.
No matter the location of the customer, the shipment estimate is that it will arrive at the pickup point closest to the sender, not the receiver.

Is it possible to skip the pick-up estimate altogether, so that it does not show where it will get delivered?

![Hentested](https://user-images.githubusercontent.com/19477449/130600801-8bc32622-0594-4252-8579-838eb88690e5.png)

**Comment by gitforfareedi** [comment]
We are working on this fix and will release new version with this fix in the end of february.
