### ISSUE TITLE
magento_testing.txt file grows bigger 

### ISSUE THREAD

**Issue by xnhinzkyx** [markant-norge/magento2-bring#20]
Can we delete/clean this file from time to time? Or remove it totally because it grows bigger everyday.

https://github.com/markant-norge/magento2-bring/blob/master/Model/Carrier.php#L451

**Comment by gitforfareedi** [comment]
This file will not be created anymore.

**Comment by gitforfareedi** [comment]
This file will not be created anymore in new version
